### ISSUE TITLE
output range of network is not consistent with report in the paper?

### ISSUE THREAD

**Issue by zjjMaiMai** [intel-isl/MiDaS#14]
Hi, thx for your great work!
I'm running your code, but network output ranges from 0 to 5000 which is not same as what you've mentioned in the paper. 
Could you please tell me if I miss some details?

**Comment by ranftlr** [comment]
Are you referring to  the statement in the paper that we shift and scale the output range of the ground truth to [0,1]? 

If yes: scaling the ground truth only influences the magnitude of the loss, not the magnitudes of the predictions. Even with a fixed ground truth range, the range of the prediction is unconstrained (apart from being positive). Together with a scale-invariant loss this means that the output scale is essentially determined by the initialization. See also #2 for a similar discussion. You can rescale the prediction by the maximum value to recover the [0,1] range, since the ground truth was scaled the same way to bring it to that range. 

If no: can you specify what statement in the paper you are referring to?

**Comment by zjjMaiMai** [comment]
@ranftlr thx for your reply！I read the paper of range [0, 1].
