### ISSUE TITLE
Slow image transformation

### ISSUE THREAD

**Issue by nickteim** [intel-isl/MiDaS#53]
Hej, 
I dont think this is a issue, sorry for posting like this.
But the image that goes through you model is really slow. Do you have a method for speeding it up?
Sorry again for posting it as a issue, but dont know how else to make contact.

**Comment by 3dsf** [comment]
Are you using a cuda gpu ?

What is your definition of slow?  
I run a rtx2060s which is limited by the cpu (speed and threads).  
With 640x480 images I get ~200 ms per inference with ~50 ms file saving (cv2) = ~250 ms per inference  
Is that slow ? 

When I run https://github.com/ialhashim/DenseDepth I get ~270 ms per inference (matplotlib is 2x slower at saving).  

I've never tried to improve the code of Midas (as this was my first reference for speed).  

With dense depth I had to tweak it (to make it run like Midas; for me) and to improve the inference (clearing the plot instead of over writing on each iteration) for the method I chose to use _(I also struggled to set up my gpu properly for using it -- finding the right cuda conda packages -- cupti? )_.

I'm not involved with either project, but use MiDaS consistently because it is flexible on the input image aspect ratio ( Dense depth only likes 4:3).

**Comment by ranftlr** [comment]
We have also just released a new version that also includes a smaller and faster model. Give it a try.

**Comment by nickteim** [comment]
Hey thanks for the answers.
@3dsf I use colab, so dont know the specs. The images takes between 1 to 7 seconds or even longer depending on how long I run the code. But this is also the whole proces from putting the image through the model, save it in mathplot and then convert it to JPG file. (Do you know of a faster way?)
@ranftlr thanks, I tried the new model, I guess it is a bit faster:) But it still takes about a whole second for each image.
(I am currently converting a video, so this can take days). 
I dont know if you guys are interested but a have linked the github code, but any ideas or hints to make the proces faster will be greatly appresiated, if you have any:)

link --> sorry have not refactored the code yet, so it is a bit messy: https://github.com/nickteim/Reinforcement_Learning-/blob/main/VideoTransform_MiDaS.ipynb

**Comment by ranftlr** [comment]
@nickteim According to our experiments, the new, small model runs in real-time even on a mobile phone. Colab has pretty capable GPUs, so even the big model should be quite fast. You might have a problem in your setup or you might be measuring things that are not related to our project. 

I ran your code and timed the blocks that are relevant (image reading + transform + MiDaS + upsampling) and can't confirm an execution time of 1-7 seconds for MiDaS. I get 0.04s per image (~25fps per second) even for the big model. Roughly double that when I also count a final memory transfer from GPU to CPU. To make your code faster, you need to find out what is slowing it down most and start from there. MiDaS in this case seems to take <4% percent of the execution time so it doesn't seem like a good candidate.

**Comment by nickteim** [comment]
@ranftlr thanks for the anwer again
I have refactored some of the code, so I dont convert to JPG file or delete anything. So now it is just the model, and saving the mathplot file. 

I timed the code (image reading + transform + MiDaS + save mathplot image) and for the first image I get about 0.17 seconds. 
But the time seems to grow linear for each image.

Time plot
![image](https://user-images.githubusercontent.com/44054399/98816873-9828c580-2429-11eb-8613-18281d05f0b7.png)
y axis is the time for each iteration
x axis is for each image

I know the array grows and might slow down the proces? But even without it, it takes longer for every iteration. 

Did you also save the images? Maybe I should use a other method to save the images?

**Comment by ranftlr** [comment]
I'm closing this issue, since it is not related to MiDaS. There are plenty of ways to write out images. In your specific case, Matplotlib is slowing down with repeated calls to plot. This is well known, [see here for a discussion](https://bastibe.de/2013-05-30-speeding-up-matplotlib.html).

**Comment by 3dsf** [comment]
hey @nickteim 

_sorry I didn't comment sooner, but I took a quick peak at what you had yesterday:_  

1. You need to clear the plot each time, otherwise you are writing over the plot each time and it will lead to an incremental increase in time (been there)  
2. switch you matplotlib code to **cv2** code and you will see good speed increases ( negates point 1 )
3. try to not open and close files.  Don't let this stop you from saving checkpoints, just don't reopen the same information you just put in a file 
4. clean up your code as much as possible before asking for help,  for example, the redundancies in your imports...

if you want further clarification, find me on reddit at 3dsf

**Comment by nickteim** [comment]
@3dsf Nice, thanks for the tips, I will try it out
